package com.image.recognition.algorithms;

import java.util.Base64;
import java.util.LinkedList;
import java.util.List;
import java.util.logging.Logger;

import com.image.recognition.handlers.Match;
import com.image.recognition.utils.Utils;

public class CatImageRecognition extends ImageRecognition {
	
	private static final Logger logger = Logger.getLogger(CatImageRecognition.class.getCanonicalName());
	
	final static String PERFECT_CAT_IMAGE_FILENAME = "perfect_cat_image.txt";
	
	final static String PERFECT_CAT_IMAGE_BASE64 = "KyAgICAgICAgICAgICArCisrKyAgICAgICAgICsrKwogKysrKysrKysrKysrKwogKysgICAgICAgICArKworKyAgKyAgI"
			+ "CAgKyAgKysKKysgKysrICAgKysrICsrCisrICAgICAgICAgICArKwogKysgICArKysgICArKwogKysgICAgICAgICArKwogI"
			+ "CsrICsgICArICsrCiAgKysgICsrKyAgKysKICAgKysgICAgICsrCiAgICAgKysrKysKCiAgICAgICAgICAgICAgIAo=";
	
	final static String IMAGE_WITH_CATS_BASE64 = "KysrKysrKysrKysrKysgKysrKysgICsrKysrICArKysrKysrKysrKyArKysgKysrKysrKysrKysrKysrKysrKysrKyArKysrKysrICsrICsrICAgICAgICAgICAgICsrKysrKworKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKyArKysrKyAgICAgICAgICAgICsrKysrKysrKysrKyArKysgICsgKysrKyAgICAgICAgICsrKysrKysrCisrICsrKysrKysgKysrKysrKysgKysrKysrKysrKysrKysrKysrKysrKysrKysrKyAgICAgICAgICsrKysrKysgKysrICsrKysrKysrICsrICsrKysrKysrKysrKysgKysgKysKKysrKysrKysrKysrKysgKyArICsrKysrICsrKysrICsrKysrKyArKyArKysrICsrKysrKysrKysrKysgKysrKyArKysgKysrKyArKyArKysgKysgICAgICAgICArICArKyArKworICsrKysrKysrKyArKysrKysrKysrKysrKysrKysgKysrKyArKyAgICsgKysrKysgICAgICAgICArKyArKysgICsrKysrKysgKysrKyArKysrICArICAgICArICArKysrKysrCisrKysgKysrKysrKysrICsrKysrKysrKysrKysrICsrKyArKysrKysrKysrKysrICArICAgICArICsrKysrKysrKysrKysrKysrKysrKysrKysgKysrICAgKysrICsrKysrKysKKysrKysrKysrKysrKyArKysrKysrKysrKysrKysrKysrKysgICArKysrKysgKysgKysrICAgKysrICsrKysrKysrKysrICsgKysrKysrKysrKyAgICAgICAgICAgKysrICsrKworKyArKysrKysrKysrKysrICsrKysrKysrKysrICsrKysrKyArKysrKysrKysrKyAgICAgICAgICAgICsrICsrKysrKysrKysrKysgKysrKyArKyAgICsrKyAgICsrICArKysrCisrKysrICsgICsrKysgKysrKyArKysrKysrKysrKysrKyAgKysrKysrKysrKyArKyAgICsrKyAgICsrICsrKysrKysrKyArKysrKysgKyArICsrICAgICAgICAgKysgKysrICsKKysrKysrKysrKysrKysrKyArKysrKysrKyArKysrKysrKysrKysrKysrKysgICsrICAgICAgICAgKysgKysrKysrICArKysrKysrKysrKysgICsrICsgICArICsrICArKysrKworKysrKysgKysrKyArKysrKysrICsrKysrKysrKysrKysrKyArKysrKysgICsgICsrICsgICArICsrICArICsrKysrKysrICsrKysrKysrICAgKysgICsrKyAgKysgICsrICArCisrKysrKysrKysrKysrKysrKyArICArKysgKysrKysrKysgKysrICsrKysrICAgKysgICsrKyAgKysgICsrKysrKysrKyArKysrKysrKysrICAgKysgICAgICsrICAgICsrKysKKysrKysgKysrKysrKysrKyAgKyArKysrKysrKysrKyArKysrKysrKyArKysrICAgKysgICAgICsrICAgICArKysrKysrKysrKysrKysgKysgICAgICsrKysrICAgICArKyArKworKyArICsrKysrICsrICsrICsrKysrKysrKyArICsrKysrKysrKysrKysrKysgKyAgICsrKysrICAgICArKysrKysrKysrICsrKysrKysrKyAgICAgICAgICAgICsgICsrKysKKysrKysrKysrKyArKysrKyArKysrKysrKysrKysrKysrKyArKysgKysrKyArICAgICAgICAgICAgICAgICsgKysrKyAgKysrKysrKysrKysgICAgICAgICAgICAgICArKysrKworKysrKysrKysrKysgICsrKysrKysrKysrKysrICsrKysrKysrICsrKysgKysgICAgICAgICAgICAgICArKysrKysrICsrKysrKysrKysrKyAgKysgKysgKysrKysrICsgKysrCisrKysrKysrKysrICsrKysrKysrKysrKysgKysrKyArKysrKysrKysrKysrKysrKysrKysrKysrKysrICsrKysrKysrKysrKysrKysrKysrKysrICsrKysrKysrICsgICsrICsKKysrKysrKysrKyArKysrICsrKysrICsrKysrKysgKyArKysrKysrKysrKysrKysgICsrKysrKysrKysrKysrKysrKysrKysrICsrKysrKysgKysrICsrKysrKysrKysrKysrKworKysrKyArKysrICsrICsgKysrKysrKyArKysrKysrKysrKysrKysgKysgKysrKysrKysrKysrKysrKysrKysrKyArKysrKyArKysrKyArKysrKysrKysrKysrKyArKysrKysrCisrKysgICsrICsrKysrKysrKysrKysrKysrKysrKysrICsrKysrICArKysrKysrKysrKysrKysrKysgKysrKysrKysgICsrKyArKysrKysrKysrKysgICsrKysrKysrKysrKysKKysrKysrKysgKysgKysrKysrKysrKyArKysrICsrICsrKyArKysrKysrKysrKysrKysrKysrKysrKysgKysrICsrKyAgKysrICArKysrKysgKysgICsrICsrICsrKysrKysrKworKysrKysrKyArKysrKysrKysrKyArICsrKyArKysrKysrKysrKysrKysrKysrKysrKyAgKysrKyArICsrKyArKysrKysrKysrKysrKysrKysrKysrKysrICArKysrKysrKysKICArICsrKysrKysgKysrKysrKysrKysrKysrKysgKyArKysgKysrKysrKysgKysrKysrKysrKyArKysrICsgKysrKysrKysrKysrKysrICsrKysrKysrICsrKysrKysrKysgKworKysrKysrKysrKysrKysgKysrKysrKysgKysrKysrKysrKysrKysrKysrKysgKysrKyAgKyArKysrKysrICsrKyArKyArKysrKysrKysrKysrKysrKysrKysrKysgKysrKyArCisrICsrKysrKysrKyAgKysrKysrKysrKysgKysrKysrKysrKyArKysrKysrKysrKysrICsrKysrICArKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrICsrKysrKysrKysKKysrKysrKysrICArKysrKysrKysgICsrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrICsrKysrKysrICsrKysrKysrKyArKysrKysrKworKysrKyArKyArKysrKysrKysrKysrICsrKysrKysrKysrKysrKysrKysrKysrKysrKyArKysrKysgICsrKysrKysrKysrICsrKysrKyArKyArKysrKysrKysrKysrKysrICsrCisrKysrKysrICsrKysrKysrKysrKysrKysrKysgKysrKysrKysrKysrKysrKyArKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrICsrICArKysKKysrKysrKysrKysrKysrICsrKysrICsrKysgKysrKysgKysrKysrKysrICsrKysrKysrKysgKysrKysrKysrICsrKysrKysrKysgKyArKysrKysrKysrKysrKysrKysrICsrKworKyArKysgKysrKysrKysrKysrICsrKysrKysrKysrKysgKysrKysrKysrKysrKysrKysrKysrKysgKysrKysrKysrKysrKyArKysgKysgKysrKyArICsrKysrICsrKyArKysrCisrKysrKysgKysgKyAgKyArKysrKysrKysrKysrKysgKyArKysrICsrKysgKysrKysrKysrICsrKysrKysrKysrKysrKyArKysrKysrKysrKysrKysrKyArKysrKyAgKysgKysKKysrKysrKyArKysrKysrKysrKysrKysrKysrKysgKysrICArICsgKyArKysrKysrICsrKysrKysrKysrKysrKyArKysrKysrICsgKysrKysrKysrKysrKysrKysrKysrKysrKworKysrICsrKysrKysrICsrKysrKysrKyArKysrKysrICAgKysrKysrKysrKysrKysrKysrKysrKysgKysgKysrICsrICsrICsgKysrKysgICsrKysrKysrKyArKysrKysrKysrCisrKysrKyArKysrKysgKysgKysrKysrKysrKyArKysrKysrKysrKysrKysgICsrKysrKysrKysrKysgKyArICsgKysrKysrKyArICsrKysrKysrKysrKysrKysrKysrKysrKysKKysrKysrKyArKysrKysgKysrKysgKysrKysrKyArKysrKyAgKyArKysrICsgKysrKysrKysgKysrKysrKysrKysrKysrKysgKysrICsrKysrICsrKysrICsrKysgICArKysrKworKysrKysrKyArKysrKysrKysrKysrKysrKysrICsrKysgKysrICsrKysrKysrKysgKyArKysrKysrKysrICsrKysrICsrKysrKysgKyArKyArKysrICsrKysrKysrKysrKyArCisrKysrKysrKysrKysrKysgKysrKysrKysrKysrKysgKysrKysrKysrKysgKysrKysrKysrKysrKysrICsrKysrKysrKysrKysgKysrKysrKysrKysrKysrKysrKysrKysrKysKKysrICsrKysrKysrICsgKysrKysrKysgKysrKysrKyAgKysrKysrKysrKysrKysrKysrKyArKysrKysrICsgKysrKyArKysrICsrKysrKysrKyAgKysrKysrKysrKysrICsrKworKysrKysrKysrKysgKyArKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrICsrICsrICsrKysgKysrKysrKysrKysrKyArKysrKysgKysrKysrKysrKyArKysrKysrKysrCiArKyArKysgKysrKysgKysrKysrKysrKysrKysrKysrKysgKysrKysrKyArKysrKysrKysgICsrKysrKysgKysrICsrKysrKysrKysrKysrKysrKyArICsrKysrKysrICsrKysKKysrKysgKysrKysrKysrKysgICsrKysrKysrKysrKysrKysrKysrKysrKysgICAgICArICAgICArKysrKysrKysrKysrKysrICsgICsrKyAgKysrKysrKyArKysrKysrKysrKworKysrKysrICsrKysrKysrKysrKyArKyArKysrKysrKysrKysrKysrICsrKysgICAgICAgICArKysrKysrKysrKysrKysrKysrKysrKysrKysgKysrKysrICsrKysrKyAgKyArCisrKyArKyArKyArKysgKysrKysrKysrKysrKysrKysrKysrKysrKysrKyArKysrKysrKysrKysrICsrKysrKysrKysgKysrKysrKysgKysrKysrKysrICsrKyArKysgICsrKworKysrKysrICsrKysrKysrKysrICsrKysrKysrKysrKysrICsrICArKysgKysgICAgICAgICArKyArKysrKyArKysrKysrKysrKyArKysrICArKysrICArKysrKysrKysrKysKKysrKysrKysgKysrICsrKysrKyAgKysrICsrKysrICsrKysrKyArKysrKysgICsgICAgICsgICsrKysgKyArKysrKysrKyArKyArKysrKysrKysrKysrKysrKysrKysgKysrKworKysrKyAgKyArICsrKysrKysrKysrKysrICsrKysrKysrKysrKysrKyArKyArKysgICArKysgKyArKysrKyArKyArICsrKyArKyArKysrKysgKysrKysgKysrKyArKysrKyArCiArKysrICsrKysgKysrICsrKysrICsrKysrKysrICsrKysrKysrKysrKysrICAgICAgICAgICArKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysgKyArKysrICsKKysgKysgKysrKyArICsrKysgKysgKysrKysrKysrKysrKysrKysrKysrICsrICAgKysrICAgKysgKyArKysrKysrKysgKyArKysrKysrICArKysrKysrKysrKysgKysrKysrKworKysrKysrKysrKysrKysgKysrKysrKysrKysrKysrKysgKyArKysrKysgKysgICAgKyAgKyArKyArKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKyArKysrCisrKysrKysrKysrICsrICsrKysrKysrKysrKysrKysrKysrICsrKysrKyAgKysgICAgICsgKysgICsrKysrICsrKysrKysrICArKysrKysgKysgKysgICAgICAgICAgICAgICsKKysrKysrKysrKysrKysrKyAgKysrKysrICsrKysrKysrKysrKysgKysgICArKyAgKysgICArKyAgKysrICsrKysrKysrKysrICsrKysrKysrKysrKysrICAgICsgICAgKysrKworKysrKysrKysrKysgKysrKyArKyArKysrKysrKyArKysrKysrICsrKysgICArKyAgICAgKysrICAgKysgKysrKysrKysrKysrKysrKysrKysrICsgKysrKysrKysrKyArKyArCisrKysrICsrKysrKysrICsrKysrKysrKysrKysrKysrKysrKysrKysrICAgICAgKysrKysgICAgICsrKysrKysrICsrKysrKysrKysrKysrKysrKyArKyAgICAgKyAgICsrICsKKysgKysrICsrKysrKysrKysrKysrKysrKysrKysgKysrKyArKysrKysgICAgICAgICAgICAgICAgKyArICsrKysrKysrICsrKysrKyArKysrICsrKysgICsgICAgICsgICsrKworKyArKysrKysrKysrKysgICsrKysrKysrKysrKysrKysrKyArKyArKyAgICAgICAgICAgICAgICArKysgKysrKysrKysrKysrKysrICsgKysrKysrKyArKysgICArKysgKysrCisrKysrKysrKysrKysgKysrKysrKysrKysrKysrKysrKysrKyAgICsrKysrKysrKysrICsrKysrICsrKysrKysrKysrKysrKysrKysgKysrKysrICsrICsgICAgICAgICArKysKKyArKysgKysrICsrKysrKysrKyAgKysrKysgKysrKysrICsrKysrKysrKysrICsrICsrKysgKysrICsrKyArKysrKysrKysrKyArKysrKysrKysrICsrICAgKyArICAgKysgKwogICsrKysrKysrKysrKyArKyArKyArKysgKyArICsgKyArICArKysrKysrICsrKysrKysrICsrKyArKysrKysgKysrKysrKysrICsrKysgKysrKysgKysgICAgICAgICArKworKysrKysrKyArICsrKysrICsrKyArKysrICsrKysrICArKysrKysrKysrKysgKyAgKysrKysrKysrKysgICsrICsrKysrKysrKysrKysrKyArKysgICsrICsgICArICsrICArCiArKysgKysgICsrKysrKysrKysrICsrKysrKysrKysrICsrKysrKysrKysrKysrKysrKysrKyArKysrKyArKysrKysrKysrKysrKysrKysrKysrKyAgKysgICsrKyArKysgICsKICsrKysgKysrICsrKysrKysrKysrKysrKysrKysrKysrKysrKyArKysrKysrKysrKyArKysrKysrKysrKysgKysrKysrKysrKyArICsgKysrKyArICAgKysgICAgICsrICAgKworICsrKysrKysrKysrKysrKysrKysrKysgICsrKysrICArKysrKysrICsrKysrKysrKysrKysgKysrKysrKysrKysrKysrKysrKysrKysrKysrICsgICAgICsrKysrICAgICArCisrKysrKysgKysrKysrKysrKysrKysrKysrKysrICsrKysrKysrKysrKysrICsrKyArKysrKysrKysrKysrKysrKysrKysrICsgKysrKysrKysrKyAgICAgICAgICAgICAgICsKKysrICsgKysrKyArICsrICsgKysrKysgKysrKysrKysrKysrKysrKysrKysrKysgICsrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrICAgICAgICAgICAgICAgKwogKysrKysrICsrKysrKysrKysrKysrKysrKysrKysrKysrICsrICsgKyArKysrKysrKysrKysrKysrKysrKysrKysrKysrICsrKysrKysrKysrICsgICsrKysrKysrKysrKysrCisrKysrKysrKysgKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKyArKysgKysrICsgICsrKysrKysgKysrKysrKysrKysgICsrKyArICsrKysrKysrKysrICsrKysrKwogKysrKysrKysrKysrKysgKysrKysrKyArKyArICsrKysrICArKysrKysrKysrKysrICsrKysgKysrICsrKysrKysgKysgKysrKysrKysgKysrICsrKysrKysgKysrKysrKysrCisrICArKysrKysrKyArKysrKysrKysgKysrKysrKysrICsrKysrICsrKysrKysrKyArKysrICsgKyArKysrKysrKysgKysgICsrKysrKysrKysrICsrKyArICsrKysrKysrICsKKysrKysrKysrKysrKyArKysgKysrKysrKysrKysrKysrKyArKysrKysrKysrICsrKysrKysrKysrKysrKyArKysrKysrKysrKyArKysgKysrKysgKysrKysrKyArKysrKysrKworKysrKysrKysrICsrKysrKysrKysrKysrKysrKysrKysrKysgKysrKysrICsrKysrKysrKysrKysrKysgKysrICsrICsrICsrKysrKysrKysrKysrKysrKysrKysrKysrKysrCisgKysrICsgKysrKysrKysrKysrICsrKysrKyArKyArKysrKysrKyArKysrKysrKysrKysrKysgKysrKysrKysrKysrKysrKysgKysrKysgKysrKysrKysrKysrKysrKysrKworKysrICsrICsrICsrKysrKyAgKysrICsrKysrKysrKysrKysrICsgKysrKysrKysrKysrKysrKysrKysrKysrKysrICsgKysrKysgKysrKysrKysrKysrKysrKysrKysgKysrCisgKysrKyArKysrICsrKysrKysrKysrKysrKysgICsrKysrKysrKysrICsgKyArKyArKysrKyArICArKyArKysgKyArKysrKysrKysgKysrKysrKysrICsrKysrKysrICsrKysKKysrKysrICsrKysrKysrKysgKysgKysgKysrKysrKysgKysrKysrKysgKysrKysgICAgKyArKysrKysgKysrKysrICsrICsgKyAgKysrKysrKyArKysrICsrKyArKysgKysrKworKysrKysgKysrKysrKysrKysrKysrKysrKysrICsrKyArKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysgKysrKysrKysrKysrKysrKysrKysrKysgKysgKysrCisrKysrKysrKysrKysrICsrKysrKyAgKyArKysrKysrKysrKysgKysrKysgKysrKysrKyArICsgKysrKysrKyArKysrKysrKysrKysrKyArKyArKysrKysrKysrKysrKysrKysKKysrKysrKysrKysrKysrICsrKysrKyArICArKyArICsrKysgKyArKysgICsrKysrICsrKysrKyArKysgKysrKysrKysrKysrKysrKysrICsrKysrKysrKysrKysrKyArKysrKworKyArKysrKysrKysrICsrKyArKysrKysrKysgKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKyAgKysrKysrKysrICsrKysrKysrKysrKysrKyArKysrKysrKysrKysrCiArKysrICsrKysrKysrICsrICsrKysrKysrKyArKysrKysrKysrKysrICsrKysrICsrKysrKysrKyAgKysgKysrKysrKysrKysrKysrKysrICsrKyArKysrKysrKyArICsrKysKKysrICsrICsrKysrKysrKysrKysrKysgKysrKysrKysrKysrKysrKysrKyArKysrKysrKysrKysrKysrKysrKysgKysrICsrKyArKysrKysrKyArKysrKysrKysrICsrKysrKworICsgKysrKysrKysrKysrKysrKysrKysrKysrKysrKyArKysrICsrKysrKysrKysgICAgICAgICAgICAgKysrKyArKyArKysrKyArKysrKysrKysrKysrKysrKysrKysgKysrCiArKysgKysrKysrKysrKysrKyArKyArKysrKysrKysrKysrKysrKysgKyArKysgKysrICAgICAgICAgKysrKysgKysrKysrKysrKysrICsrKysrKysgKyArKysrKysgICArKworKysrKysrKyArKysrICsrKysrKysrKysgKysrKysrKysrKysrKysrKysrKysrKyArKysrKysrKysrKyArICsrKysrKysrKysrKysrICsrKysrKysgKysrKysrICArKysrKysrCisrKysrKysrKysrKysrICsrKysrICsrKysrKysrKysrKysrKysrKyArKysrKysrICsrICAgICAgICAgKysgKysrKysrKysrKysrKysrKyAgICsrKyArKysrKysrKysrKysrKysKKysrKyArKysrKysgKysrKyArKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKyAgKyAgICAgKyAgKysrKyArKysrKyArKyAgKysrKysrKyArKyAgICAgICAgICAgICArCiArKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKyArKysgKysrICAgKysrICsrKysrKysrKysrKyArKysrKysrKysrICsrKyAgICAgICAgICsrKysKKyArKysrKysrKyAgICsrKysrKysrKysrICsrKysrKysrKysgKyArKysrKyArKyArKyAgICAgICAgICAgKysrKyArKysrKysrKysrKysrKysrKysrICsrKysrKysrKysrKysgKworKysrKysrKyArKysrKysrKysrKysrKysrKysrKyArKysrKysrKysgICsrKysrKyArKyAgICsrKyAgICsrICsrKysrICsgKysrKysrKysrKysrKyAgKysgICAgICAgICArKyArCisrKysrKysrKysrKysrKysrKysrKysgKysrKysrKysrKysrKyArKysrKysgKysrICsrICAgICAgICAgKysgKyArKysrKysrKyArKysrKysrKysrKyArICArICAgICArICArKysKKyArKysrKysrKysrKysrICArKysrKysrKysrKysrKysrKysrKysrKysrKysrKysgICsrICAgICArICsrICAgICsrKysrKysgKysrKysrKyArICsrKysgKysrICAgKysrICsrKworKysrICArKysrKysrKyArKyArKysrKysrKysrKysrKysgKysrKysrKysrKysrKyAgKysgICsrKyAgKysgICsrKysrKysrKysrKysrKysrKysrKysrKyAgICAgICAgKyAgKysrCiArKysrKysgKysrKysrKysrKysrKysrKysrKyAgKysgKysgICsrKyArICsrICArICAgKysgICAgICsrICAgKysrKysrKysrKyArKysrKysgKysrICArKyAgICsrKyAgICsrICsKKysrKysrKysrKysrKysrKysrKyArKysrKysrKysrICsrKysrKysrKysrKysrKysgICAgICsrKysrICAgICArICsrKysrKysrKysrKyArKysrKysrICsrICAgICAgICAgKysgKworKysrKysrKysrKysrKysrKysgICsgKysgKysrKysrKysrKysrKyArKysrKysrKyAgICAgICAgICAgICAgICsgKysrKysrKysrKysrKysgKyArKysgICsrICsgICArICsrICArCiArKysrKysgKysrKysrKysrKysrKysrKysrKysrKysrKysgKyArKyArKysrKysgKyAgICAgICAgICArICAgKysgKysrKysrKysrKysrKyArICsrKyAgKysgICsrKyAgKysgICsKKysrKysrICsrKysrKysrKysrKysrKyArKysrKysrICsrKysrKysrICsgKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrICAgKysgICAgICsrICAgKworKysrKysrKysrKysrKyArKysrKyAgKysgKysrKysrKysrICsrKysgKysrKysrKysrKysrKysrKysrKysrKysrKysgKysrKysrKysrKysrKysrKysgICAgICsgKysrICAgICArCiAgKysrKysrKysrKysrKysrKysgKysrKyArICsrKysrKysrKysgKysrKysrKysrKysrKysrKysrKysrKysgKysrKysrKysrKysrKysrICArKysrKyAgICAgICAgICAgICAgICsKKysgKysrKysrKysrKysrKyArKysrICsrKyAgKysrKyAgKysrKysrKysrICsrKysrKysrKysrKysrKysrKysrKysrICsrKysrKysrICsrKysrKysrICAgICAgICAgICAgICAgKworKysrKysrKysrKysrKysrKysrKysrKysrKyArKysrKysrICsrKysrKysrKysrKysrKysrKysrKysgKysrKysrKysgKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrCg==";
	
	static Byte [][] perfectCatImage;
	
	static {
		
		perfectCatImage = Utils.getTextMatrixFromBase64(PERFECT_CAT_IMAGE_BASE64);
		
//		TODO: Load it from a resource file
//		try {
//			String file = Files.toString(new File (PERFECT_CAT_IMAGE_FILENAME), Charsets.UTF_8);
//			perfectCatImage = Utils.getTextMatrix(file);
//		} catch (IOException e) {
//			e.printStackTrace();
//		}
		
	}
	
	/**
	 * @param targetImage	Base64 encoded text image file
	 * @param threshold		The threshold with which the images are matched
	 */
	public CatImageRecognition (String targetImage, Double threshold) {
		super(perfectCatImage, Utils.getTextMatrixFromBase64(targetImage), threshold);
		logger.info(new String(Base64.getDecoder().decode(targetImage.getBytes())));
		//super(perfectCatImage, Utils.getTextMatrixFromBase64(IMAGE_WITH_CATS_BASE64), threshold);
	}

	@Override
	public List<Match> find () {
		
		Byte [][] srcImage = getSourceImageMatrix();
		Byte [][] targetImage = getTargetImageMatrix();
		
		Double minSAD = Double.MAX_VALUE;
		
		List<Match> matchPositions = new LinkedList<Match> ();
		
		int totalMatchesPossible = srcImage.length * srcImage[0].length;
		
		// loop through the search image
		for ( int x = 0; x <= targetImage.length - srcImage.length; x++ ) {
		    for ( int y = 0; y <= targetImage[0].length - srcImage[0].length; y++ ) {
			    Double SAD = 0.0;
			    Double confidence = 0.0;
			    int numMatches = 0;
				// loop through the perfect image
				for ( int j = 0; j < srcImage[0].length; j++ ) {
		            for ( int i = 0; i < srcImage.length; i++ ) {
		            	byte targetImgVal = targetImage[x+i][y+j];
		                byte srcImageVal = srcImage[i][j];
		                if (targetImgVal == srcImageVal) {
		                	numMatches++;
		                }
		                SAD += Math.abs(targetImgVal - srcImageVal);
		            }
			    }
//				logger.info("SAD: " + SAD);
//				if (numMatches > 0) {
//					logger.info("numMatches: " + numMatches);
//				}
		        // save the best found position 
//		        if ( minSAD > SAD ) {
//		            minSAD = SAD;
//		            // send the match with min SAD
//		            matches.add(new Match (x, y, SAD));
//		        }
				
				//save the best position
				if (minSAD > SAD) {
					minSAD = SAD;
				}

				//calculate confidence so far
				confidence = ((1.0 * numMatches) / totalMatchesPossible) * 100.0;
				
				//check if the confidence is greater than the threshold, if not break
				if (confidence >= getThreshold()) {
					matchPositions.add(new Match (x, y, confidence));
				}
		    }
		}
		return matchPositions;
	}

}
